services:
  - type: web
    name: invoice-extractor
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: invoice-extractor-disk
      mountPath: /app/data
      sizeGB: 1
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - "**"
        - "!docs/**"
        - "!tests/**"
        - "!*.md"
