services:
  - type: web
    name: invoice-analyzer-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    disk:
      name: invoice-analyzer-disk
      mountPath: /app/data
      sizeGB: 1
